SET SERVEROUTPUT ON;

DROP TABLE INTERNET_PLAN;

CREATE TABLE INTERNET_PLAN
( PLAN_ID VARCHAR2(7),
  ISP VARCHAR2(20),
  SPEED_MBPS NUMBER(4,2),
  PLAN_DURATION_MONTHS NUMBER(2)
);

INSERT INTO INTERNET_PLAN VALUES('2MBUN3M','RELIANCE',2,3);
INSERT INTO INTERNET_PLAN VALUES('1MBUN2M','RELIANCE',1,2);
INSERT INTO INTERNET_PLAN VALUES('2MBUN3M','AIRTEL',2,3);
INSERT INTO INTERNET_PLAN VALUES('4MBUN2M','VODAFONE',4,2);
INSERT INTO INTERNET_PLAN VALUES('2MBUN2M','BSNL',2,2);

DECLARE
TYPE planArrType IS TABLE OF  INTERNET_PLAN%ROWTYPE;

plan_group1 planArrType;

BEGIN
--EXECUTE IMMEDIATE 'SELECT * FROM INTERNET_PLAN WHERE ROWNUM < 4' BULK COLLECT INTO plan_group1;
EXECUTE IMMEDIATE 'SELECT * FROM INTERNET_PLAN SAMPLE(30)' BULK COLLECT INTO plan_group1 ;  -- 30% OF ROWS

FOR i IN plan_group1.FIRST..plan_group1.LAST
LOOP
DBMS_OUTPUT.PUT_LINE(plan_group1(i).PLAN_ID);
END LOOP;

END;
/