DECLARE
  CURSOR C1 ( t_emp_id IN EMPLOYEES.EMPLOYEE_ID%TYPE := 0 , t_row OUT EMPLOYEES%ROWTYPE , t_out_cur OUT SYS_REFCURSOR )
    RETURN EMPLOYEES%ROWTYPE
  IS
    SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = t_emp_id;
  outrows EMPLOYEES%ROWTYPE ;
  outcursor SYS_REFCURSOR;
BEGIN
  OPEN outcursor FOR SELECT 'I_AM_GOING_OUT' a FROM DUAL;
  OPEN C1(110, outrows , outcursor);
  LOOP
    EXIT
  WHEN C1%NOTFOUND;
    FETCH C1 INTO outrows;
  END LOOP;
  CLOSE C1;
END;
/