CREATE OR REPLACE TRIGGER DDL_TRIG_GENERAL AFTER DDL ON SCHEMA
  DECLARE
    ts    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
    q_out VARCHAR2(1000) := 'IP ADDRESS OF THE CLIENT: '||ORA_CLIENT_IP_ADDRESS ||CHR(10)|| 'DATABASE LOGIN USER: '||ORA_LOGIN_USER ||CHR(10)|| 'NAME OF THE DATABASE: ' || ORA_DATABASE_NAME ||CHR(10)|| 'DATABASE OBJECT: '||ORA_DICT_OBJ_NAME ||CHR(10)|| 'TYPE OF EVENT: '||ORA_SYSEVENT;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('DDL AT '||ts);
    DBMS_OUTPUT.PUT_LINE(q_out);
  END;
  /
  
SET SERVEROUTPUT ON;

CREATE TABLE a_hello AS  ( SELECT 1 a , 'HELLO' word  FROM DUAL );
DROP TABLE a_hello;