SET SERVEROUTPUT ON;
DECLARE

TYPE  emp_id_type IS TABLE OF JOB_HIST1.EMPLOYEE_ID%TYPE;
emp_id emp_id_type;
updt_q VARCHAR2(200);
incr NUMBER(4);

BEGIN
incr := 30;
updt_q := 'UPDATE  JOB_HIST1 SET END_DATE = END_DATE + :INCR WHERE JOB_ID LIKE ''%CLERK%''  RETURNING EMPLOYEE_ID INTO :e';

EXECUTE IMMEDIATE updt_q USING incr RETURNING  BULK COLLECT INTO emp_id;

FOR i IN  emp_id.FIRST..emp_id.LAST
LOOP
DBMS_OUTPUT.PUT_LINE(emp_id(i));
END LOOP;
END;
/

