
  CREATE TABLE HR.EMPLOYEES_KJN 
   (	EMPLOYEE_ID NUMBER(6,0), 
	FIRST_NAME VARCHAR2(20), 
	LAST_NAME VARCHAR2(25) CONSTRAINT EMP_KJN_LAST_NAME_NN NOT NULL ENABLE, 
	EMAIL VARCHAR2(25) CONSTRAINT EMP_KJN_EMAIL_NN NOT NULL ENABLE, 
	PHONE_NUMBER VARCHAR2(20), 
	HIRE_DATE DATE CONSTRAINT EMP_KJN_HIRE_DATE_NN NOT NULL ENABLE, 
	JOB_ID VARCHAR2(10) CONSTRAINT EMP_KJN_JOB_NN NOT NULL ENABLE, 
	SALARY NUMBER(8,2), 
	COMMISSION_PCT NUMBER(2,2), 
	MANAGER_ID NUMBER(6,0), 
	DEPARTMENT_ID NUMBER(4,0), 
	 CONSTRAINT EMP_KJN_SALARY_MIN CHECK (salary > 0) ENABLE, 
	 CONSTRAINT EMP_KJN_EMAIL_UK UNIQUE (EMAIL)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 CONSTRAINT EMP_KJN_EMP_KJN_ID_PK PRIMARY KEY (EMPLOYEE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 CONSTRAINT EMP_KJN_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
	  REFERENCES HR.DEPARTMENTS (DEPARTMENT_ID) ENABLE, 
	 CONSTRAINT EMP_KJN_JOB_FK FOREIGN KEY (JOB_ID)
	  REFERENCES HR.JOBS (JOB_ID) ENABLE, 
	 CONSTRAINT EMP_KJN_MANAGER_FK FOREIGN KEY (MANAGER_ID)
	  REFERENCES HR.EMPLOYEES (EMPLOYEE_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;