SET SERVEROUTPUT ON;
DECLARE
  a1 EXCEPTION;
  a2 EXCEPTION;
BEGIN
  
    DECLARE
      n  NUMBER := 6 ;
      m  NUMBER := 5;
      
    BEGIN
    
    IF n < 6 THEN
    RAISE a1;
    END IF;
    IF m = 5 THEN
    RAISE a2;
    END IF;
      NULL;
    EXCEPTION
    WHEN a1 THEN
      SYS.DBMS_OUTPUT.PUT_LINE('INNER a1');
    WHEN a2 THEN
      SYS.DBMS_OUTPUT.PUT_LINE('INNER a2');
      RAISE;
    WHEN OTHERS THEN
      SYS.DBMS_OUTPUT.PUT_LINE('INNER OTHERS');
    END;
  EXCEPTION
  WHEN a1 THEN
    SYS.DBMS_OUTPUT.PUT_LINE('OUTER a1');
  WHEN a2 THEN
    SYS.DBMS_OUTPUT.PUT_LINE('OUTER a2');
  WHEN OTHERS THEN
    SYS.DBMS_OUTPUT.PUT_LINE('OUTER OTHERS');
  END;
  
  
  