SET SERVEROUTPUT ON;

DROP TABLE PLAYER;

CREATE TABLE PLAYER (
PLAYER_CODE NUMBER(5),
PLAYER_NAME VARCHAR2(20),
PLAYER_COUNTRY VARCHAR2(15),
RANK NUMBER(3));

INSERT INTO PLAYER VALUES (03455,'SACHIN','INDIA',2);
INSERT INTO PLAYER VALUES (03475,'WAUGH','AUSTRALIA',1);
INSERT INTO PLAYER VALUES (04412,'COOK','ENGLAND',4);
INSERT INTO PLAYER VALUES (04432,'DHONI','INDIA',6);

<<main>>
DECLARE
CURSOR cur1 IS	SELECT PLAYER_NAME FROM PLAYER WHERE PLAYER_COUNTRY='INDIA' FOR UPDATE;
player_name PLAYER.PLAYER_NAME%TYPE;
rank PLAYER.RANK%TYPE;

FUNCTION set_rank ( player_name IN PLAYER.PLAYER_NAME%TYPE ) RETURN NUMBER IS
rank NUMBER(3);
BEGIN
IF player_name = 'SACHIN'  THEN
rank := 1;
END IF;

IF player_name = 'DHONI' THEN
rank := 2;
END IF;

return rank;
END;

BEGIN
OPEN cur1;

LOOP
FETCH cur1 INTO player_name;
EXIT WHEN cur1%NOTFOUND;
rank := set_rank( player_name);
UPDATE PLAYER SET RANK = main.rank WHERE CURRENT OF cur1;

END LOOP;

END;
/