DECLARE
n1 NUMBER(10) := 10;
n2 NUMBER(10) := 10;
c1 VARCHAR2(1):= 'A';
c2 VARCHAR2(1):= 'A';

BEGIN

IF n1 != n2 AND  c1 = c2 THEN
 IF n1 = c1 THEN
  DBMS_OUTPUT.PUT_LINE('EQUAL');
  END IF;
ELSE
DBMS_OUTPUT.PUT_LINE('UNEQUAL');

END IF;
EXCEPTION

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR -'|| SQLERRM);

END;
/