SET SERVEROUTPUT ON;

DROP TABLE BREAKFAST;
CREATE TABLE BREAKFAST (
ITEM VARCHAR2(10),
PRICE NUMBER(6,2),
QUANTITY NUMBER(2)
);

DECLARE
b1 BREAKFAST%ROWTYPE;
b2 BREAKFAST%ROWTYPE;
b3 BREAKFAST%ROWTYPE;
b4 BREAKFAST%ROWTYPE;
BEGIN

b1.ITEM := 'Idli';
b1.PRICE := 35.00;
b1.QUANTITY := 2;

b2.ITEM := 'dosa';
b2.PRICE := 45.00;
b2.QUANTITY := 2;

b3.ITEM := 'saada dosa';
b3.PRICE := 40.00;
b3.QUANTITY := 2;

INSERT INTO BREAKFAST VALUES b1;
INSERT INTO BREAKFAST VALUES b2;
UPDATE BREAKFAST SET ROW = b3 WHERE ITEM = 'dosa';
END;
/