SELECT INSTR('BANANA AND ANANAS','AN',2,3) FROM DUAL;
SELECT INSTR('BANANA AND ANANAS','A',1,2) FROM DUAL;
SELECT INSTR('BANANA AND ANANAS','AN',3,2) FROM DUAL;
SELECT INSTR('BANANA AND ANANAS','AN',3,3) FROM DUAL;

