SELECT M.JRNL_NO,M.JRNL_DATE,M.BRANCH_NO,T.T_HOME_BRNCH FROM MCAD M JOIN TODM  T ON M.JRNL_NO = T.T_JRNL_NO  AND     M.JRNL_DATE = T.T_JR01_DATE AND   M.JRNL_DATE = 41563;

SELECT JRNL_NO,JRNL_DATE,BRANCH_NO,HOME_BRNCH FROM MCAD M JOIN JR01  J USING(JRNL_NO) WHERE  M.JRNL_DATE = J.JR01_DATE;

SELECT M.JRNL_NO,M.JRNL_DATE,M.BRANCH_NO,T.T_HOME_BRNCH FROM MCAD M FULL JOIN TODM  T ON M.JRNL_NO = T.T_JRNL_NO  AND     M.JRNL_DATE = T.T_JR01_DATE AND   M.JRNL_DATE = 41563;
SELECT M.JRNL_NO,M.JRNL_DATE,M.BRANCH_NO,T.T_HOME_BRNCH FROM MCAD M LEFT JOIN TODM  T ON M.JRNL_NO = T.T_JRNL_NO  AND     M.JRNL_DATE = T.T_JR01_DATE AND   M.JRNL_DATE = 41563;
SELECT M.JRNL_NO,M.JRNL_DATE,M.BRANCH_NO,T.T_HOME_BRNCH FROM MCAD M  RIGHT JOIN TODM  T ON M.JRNL_NO = T.T_JRNL_NO  AND     M.JRNL_DATE = T.T_JR01_DATE AND   M.JRNL_DATE = 41563;
