set echo on;
SELECT LPAD('VALUE',8,'*') FROM DUAL;
SELECT LPAD('VALUE',4,'*') FROM DUAL;
SELECT RPAD('VALUE',8,'*') FROM DUAL;
SELECT RPAD('VALUE',4,'*') FROM DUAL;

SELECT LTRIM('Hotel PR','Hotel ') FROM DUAL;
SELECT RTRIM('PR Hotel','Hotel ') FROM DUAL;

