SET SERVEROUTPUT ON;
DROP TABLE BILL_PAID;
CREATE TABLE BILL_PAID (
CUST_ID VARCHAR2(6),
BILL_DATE VARCHAR2(10),
BILL_AMOUNT NUMBER(10,4)
);


DECLARE

CUT_OF_DATE VARCHAR2(10) := '2014-01-05'; 
cid BILL_PAID.CUST_ID%TYPE;
DUE_DATE_EXCEEDED EXCEPTION;
PRAGMA EXCEPTION_INIT(DUE_DATE_EXCEEDED, -20006);

PROCEDURE pay_bill ( cust VARCHAR2 , dt  VARCHAR2, amount NUMBER) IS
 BEGIN
  
    COMMIT;
    IF  TO_DATE(dt,'YYYY-MM-DD')  > TO_DATE( CUT_OF_DATE,'YYYY-MM-DD' ) THEN

     RAISE_APPLICATION_ERROR (-20006,'BILL PAID AFTER DUE DATE');
   
   END IF;
   INSERT INTO BILL_PAID VALUES (cust,dt,amount);
END  pay_bill;

BEGIN
cid := 'J54677';
pay_bill(cid,'2013-12-30',1450.50);

cid := 'J54678';
pay_bill(cid,'2014-01-12',1320.00);  --will cause exception.

cid := 'J54642';
pay_bill(cid,'2014-01-05',750.50);

EXCEPTION
WHEN DUE_DATE_EXCEEDED THEN
DBMS_OUTPUT.PUT_LINE ('PENALTY CHARGED FOR CUSTOMER ' || cid);
DBMS_OUTPUT.PUT_LINE ('ERRNO = '|| SQLCODE || ' ERROR MSG IS ' || SQLERRM);
END;
/
