SET SERVEROUTPUT ON;

DROP TABLE BUS_PASS;

CREATE TABLE BUS_PASS
(
ISSUE_DATE DATE NOT  NULL UNIQUE,
PERIOD VARCHAR2(10),
VALID_DAYS_LEFT NUMBER(3),
SOURCE VARCHAR2(20),
DESTINATION VARCHAR2(20)
);

DECLARE
TYPE journeyType is RECORD ( src BUS_PASS.SOURCE%TYPE,
                             dest BUS_PASS.SOURCE%TYPE
			    );

jour1 journeyType;
                        
BEGIN

INSERT INTO BUS_PASS VALUES('25-JUN-13','MONTHLY',11,'MULUND','VASHI') RETURNING SOURCE,DESTINATION INTO jour1;

DBMS_OUTPUT.PUT_LINE (jour1.src ||'->'|| jour1.dest);
END;

/



