SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER alert_chg_glif10 
AFTER   INSERT  ON GLIF10
FOR EACH ROW WHEN (NEW.LCY_AMT > 100000)
BEGIN
DBMS_OUTPUT.PUT_LINE('TRANSACTION > 1 LAKH, AMOUNT = '||:NEW.LCY_AMT||' BRANCH = '||:NEW.BRCH);
DBMS_OUTPUT.PUT_LINE('USER = '||sys.login_user);
END;
/

INSERT INTO GLIF10 SELECT * FROM  GLIF3 WHERE BRCH LIKE '%1%';