SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER alert_chg_glif3 
BEFORE  UPDATE OR INSERT OR DELETE ON GLIF3
FOR EACH ROW

DECLARE
alert_str CHAR(30) := 'GLIF3 TABLE GETTING CHANGED';

BEGIN



DBMS_OUTPUT.PUT_LINE(alert_str||'.');


END;
/

UPDATE GLIF3 SET BRCH='01581' WHERE GL_CLASS_CODE LIKE '%00691%';

