CREATE TABLE REQ_CHG
(
DTTIME CHAR(20),
RQST_NO         CHAR(16) NOT NULL,
RQST_BR         NUMBER(5),
PROCESS_FLAG_OLD CHAR(1),
PROCESS_FLAG_NEW CHAR(1)
);

SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER alert_chg_adhp10 
AFTER   UPDATE  ON ADHP10
FOR EACH ROW
BEGIN
INSERT INTO REQ_CHG (DTTIME,RQST_NO,RQST_BR,PROCESS_FLAG_OLD,PROCESS_FLAG_NEW)  VALUES(TO_CHAR(SYSDATE,'DD-MM-YYYY-HH:MI:SS'),:OLD.RQST_NO,:OLD.RQST_BR,:OLD.PROCESS_FLAG,:NEW.PROCESS_FLAG);
END;
/

